worker_processes 1;

events {

    worker_connections 512;
    multi_accept on;
}


http {
server {
    listen 80;
    server_name fastapi_test;


    location / {
        proxy_set_header Host $http_host;
        proxy_pass http://fastapi:8000;
    }


}
}